version: '3.8'

services:
  go-service:
    build: ./go_service
    environment:
      POSTGRES_URL: "postgresql://user:pass@postgres/osm?sslmode=disable"
      OVERPASS_URL: "http://overpass-api:8080/api/interpreter"
      ML_SERVICE_URL: "http://ml-service:5000/predict"
      SAVE_TRAINING_DATA: "true"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - ml-service

  ml-service:
    build: ./ml_service
    environment:
      DB_URL: "postgresql://user:pass@postgres/osm"
    volumes:
      - ./ml_models:/app/models
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  model-trainer:
    build: ./ml_service
    command: python train_models.py
    environment:
      DB_URL: "postgresql://user:pass@postgres/osm"
    volumes:
      - ./ml_models:/app/models
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: osm
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
  ml_models: